# Generated by Django 4.2.9 on 2026-05-24 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_export', 'SAP Export'), ('utility_portal', 'Utility Portal'), ('travel_api', 'Travel API')], max_length=30)),
                ('source_row_id', models.CharField(blank=True, max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('scope_category', models.CharField(choices=[('scope_1', 'Scope 1 — Direct'), ('scope_2', 'Scope 2 — Electricity'), ('scope_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('original_unit', models.CharField(max_length=50)),
                ('original_value', models.FloatField()),
                ('normalized_unit', models.CharField(default='kg', max_length=50)),
                ('normalized_value', models.FloatField()),
                ('emission_factor', models.FloatField()),
                ('estimated_emissions', models.FloatField()),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
