# Generated by Django 4.2.9 on 2026-05-24 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emissions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='emissions_n_tenant__63bc65_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'suspicious_flag'], name='emissions_n_tenant__26f654_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope_category'], name='emissions_n_tenant__35f4c3_idx'),
        ),
    ]
